# Use container-based infrastructure
sudo: false

language: scala
scala:
   - 2.10.5
   - 2.11.7
   - 2.12.2

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk8

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.2
      jdk: openjdk6
    - scala: 2.12.2
      jdk: openjdk7

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm