# Use container-based infrastructure
sudo: false

language: scala
scala:
   - 2.10.5
   - 2.11.7
   - 2.12.0

jdk:
  - openjdk7
  - openjdk6
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

script:
  - sbt ++$TRAVIS_SCALA_VERSION test scripted
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm